update makefile: add s3 backup stuff and conditional make clean on make destroy if kubectl shows cluster up.

diff --git a/starexec-kubernetes/terraform/Makefile b/starexec-kubernetes/terraform/Makefile
--- a/starexec-kubernetes/terraform/Makefile
+++ b/starexec-kubernetes/terraform/Makefile
@@ -137,10 +137,17 @@ create-cluster:
 
 # Destroys EKS infrastructure
 destroy:
-	# make clean;
+	# run make clean if k8s stuff hasn't been shut down.
+	@if kubectl cluster-info > /dev/null 2>&1; then \
+		echo "Cluster is up. Running make clean..."; \
+		make clean; \
+	else \
+		echo "Cluster is not up. Skipping make clean."; \
+	fi
 	terraform destroy -target=module.eks -auto-approve
 	terraform destroy -target=module.vpc -auto-approve
 	terraform destroy -auto-approve
+
 
 
 
@@ -168,26 +175,208 @@ kubectl-setup:
 # S3 Backups         #
 ######################
 
-# Creates S3 bucket
+
+
+BUCKET_NAME := $(shell terraform output -raw cluster_name | tr '[:upper:]' '[:lower:]')-bucket
+REGION := $(shell terraform output -raw region)
+EFS_FILE_SYSTEM_ID := $(shell terraform output -raw efs_file_system_id)
+DATASYNC_S3_ACCESS_ROLE_NAME := DataSyncS3AccessRole
+
+# Creates S3 bucket (does nothing if already exists)
 create-s3-bucket:
-	echo "Unimplemented"
+	@echo "Creating S3 bucket: $(BUCKET_NAME)"
+	@aws s3api head-bucket --bucket $(BUCKET_NAME) >/dev/null 2>&1 || \
+	aws s3api create-bucket --bucket $(BUCKET_NAME) --create-bucket-configuration LocationConstraint=$(REGION)
+
+# Creates IAM role for DataSync to access S3
+create-datasync-iam-role:
+	@echo "Creating IAM role for DataSync to access S3"
+	@aws iam get-role --role-name $(DATASYNC_S3_ACCESS_ROLE_NAME) >/dev/null 2>&1 || \
+	aws iam create-role --role-name $(DATASYNC_S3_ACCESS_ROLE_NAME) --assume-role-policy-document file://datasync-trust-policy.json
+	@sed 's/BUCKET_NAME/$(BUCKET_NAME)/g' datasync-s3-access-policy.json.tpl > datasync-s3-access-policy.json
+	@aws iam put-role-policy --role-name $(DATASYNC_S3_ACCESS_ROLE_NAME) --policy-name DataSyncS3AccessPolicy --policy-document file://datasync-s3-access-policy.json
+	@rm datasync-s3-access-policy.json
 
 # Copies data from EFS to S3
-backup-to-s3:
-	echo "Unimplemented"
+backup-to-s3-from-efs: create-s3-bucket create-datasync-iam-role
+	@echo "Backing-up data from EFS to S3 bucket: $(BUCKET_NAME)"
+	@AWS_ACCOUNT_ID=$$(aws sts get-caller-identity --query 'Account' --output text); \
+	REGION=$(REGION); \
+	EFS_FILE_SYSTEM_ID=$(EFS_FILE_SYSTEM_ID); \
+	EFS_SUBNET_ID=$$(aws efs describe-mount-targets --file-system-id $(EFS_FILE_SYSTEM_ID) --query 'MountTargets[0].SubnetId' --output text); \
+	MOUNT_TARGET_ID=$$(aws efs describe-mount-targets --file-system-id $(EFS_FILE_SYSTEM_ID) --query 'MountTargets[0].MountTargetId' --output text); \
+	EFS_SECURITY_GROUP_IDS=$$(aws efs describe-mount-target-security-groups --mount-target-id $$MOUNT_TARGET_ID --query 'SecurityGroups' --output text); \
+	EFS_SECURITY_GROUP_ARNS="[$$(for sg_id in $$EFS_SECURITY_GROUP_IDS; do printf '"arn:aws:ec2:%s:%s:security-group/%s",' $$REGION $$AWS_ACCOUNT_ID $$sg_id; done | sed 's/,$$//')]"; \
+	EFS_SUBNET_ARN="arn:aws:ec2:$$REGION:$$AWS_ACCOUNT_ID:subnet/$$EFS_SUBNET_ID"; \
+	EFS_FILESYSTEM_ARN="arn:aws:elasticfilesystem:$$REGION:$$AWS_ACCOUNT_ID:file-system/$$EFS_FILE_SYSTEM_ID"; \
+	echo "Creating EFS Location"; \
+	EFS_LOCATION_ARN=$$(aws datasync create-location-efs --efs-filesystem-arn $$EFS_FILESYSTEM_ARN --ec2-config "SubnetArn=$$EFS_SUBNET_ARN,SecurityGroupArns=$$EFS_SECURITY_GROUP_ARNS" --query 'LocationArn' --output text); \
+	DATASYNC_S3_ACCESS_ROLE_ARN=$$(aws iam get-role --role-name $(DATASYNC_S3_ACCESS_ROLE_NAME) --query 'Role.Arn' --output text); \
+	S3_LOCATION_ARN=$$(aws datasync create-location-s3 --s3-bucket-arn arn:aws:s3:::$(BUCKET_NAME) --s3-config '{ "BucketAccessRoleArn": "'"$$DATASYNC_S3_ACCESS_ROLE_ARN"'" }' --query 'LocationArn' --output text); \
+	TASK_ARN=$$(aws datasync create-task --source-location-arn $$EFS_LOCATION_ARN --destination-location-arn $$S3_LOCATION_ARN --name EFS-to-S3-Backup --query 'TaskArn' --output text); \
+	echo "Starting DataSync task $$TASK_ARN"; \
+	EXECUTION_ARN=$$(aws datasync start-task-execution --task-arn $$TASK_ARN --query 'TaskExecutionArn' --output text); \
+	echo "Waiting for DataSync task to complete (Execution arn $$EXECUTION_ARN)"; \
+	while true; do \
+		STATUS=$$(aws datasync describe-task-execution --task-execution-arn $$EXECUTION_ARN --query 'Status' --output text); \
+		BYTES_TRANSFERRED=$$(aws datasync describe-task-execution --task-execution-arn $$EXECUTION_ARN --query 'BytesTransferred' --output text); \
+		BYTES_WRITTEN=$$(aws datasync describe-task-execution --task-execution-arn $$EXECUTION_ARN --query 'BytesWritten' --output text); \
+		echo "Task status: $$STATUS, Bytes transferred: $$BYTES_TRANSFERRED, Bytes written: $$BYTES_WRITTEN"; \
+		if [ "$$BYTES_TRANSFERRED" != "None" ] && [ "$$BYTES_WRITTEN" != "None" ] && [ $$BYTES_TRANSFERRED -ne 0 ]; then \
+			PERCENT=$$(echo "scale=2; $$BYTES_WRITTEN * 100 / $$BYTES_TRANSFERRED" | bc); \
+			echo "Task status: $$STATUS, Progress: $$PERCENT%"; \
+		else \
+			echo "Task status: $$STATUS, Progress: Calculating..."; \
+		fi; \
+		if [ "$$STATUS" = "SUCCESS" ]; then \
+			echo "DataSync task completed successfully"; \
+			break; \
+		elif [ "$$STATUS" = "ERROR" ]; then \
+			ERROR_CODE=$$(aws datasync describe-task-execution --task-execution-arn $$EXECUTION_ARN --query 'Result.ErrorCode' --output text); \
+			ERROR_DETAIL=$$(aws datasync describe-task-execution --task-execution-arn $$EXECUTION_ARN --query 'Result.ErrorDetail' --output text); \
+			echo "DataSync task failed with error code: $$ERROR_CODE"; \
+			echo "Error details: $$ERROR_DETAIL"; \
+			exit 1; \
+		else \
+			sleep 10; \
+		fi; \
+	done
+	echo "Cleaning up DataSync task and locations"; \
+	aws datasync delete-task --task-arn $$TASK_ARN; \
+	aws datasync delete-location --location-arn $$EFS_LOCATION_ARN; \
+	aws datasync delete-location --location-arn $$S3_LOCATION_ARN
 
 # Restores data from S3 back to EFS
-restore-from-s3:
-	echo "Unimplemented"
+restore-to-efs-from-s3: create-datasync-iam-role
+	@echo "Restoring data from S3 bucket: $(BUCKET_NAME) to EFS file system: $(EFS_FILE_SYSTEM_ID)"
+	@AWS_ACCOUNT_ID=$$(aws sts get-caller-identity --query 'Account' --output text); \
+	REGION=$(REGION); \
+	EFS_FILE_SYSTEM_ID=$(EFS_FILE_SYSTEM_ID); \
+	EFS_SUBNET_ID=$$(aws efs describe-mount-targets --file-system-id $$EFS_FILE_SYSTEM_ID --query 'MountTargets[0].SubnetId' --output text); \
+	MOUNT_TARGET_ID=$$(aws efs describe-mount-targets --file-system-id $$EFS_FILE_SYSTEM_ID --query 'MountTargets[0].MountTargetId' --output text); \
+	EFS_SECURITY_GROUP_IDS=$$(aws efs describe-mount-target-security-groups --mount-target-id $$MOUNT_TARGET_ID --query 'SecurityGroups' --output text); \
+	EFS_SECURITY_GROUP_ARNS="[$$(for sg_id in $$EFS_SECURITY_GROUP_IDS; do printf '"arn:aws:ec2:%s:%s:security-group/%s",' $$REGION $$AWS_ACCOUNT_ID $$sg_id; done | sed 's/,$$//')]"; \
+	EFS_SUBNET_ARN="arn:aws:ec2:$$REGION:$$AWS_ACCOUNT_ID:subnet/$$EFS_SUBNET_ID"; \
+	EFS_FILESYSTEM_ARN="arn:aws:elasticfilesystem:$$REGION:$$AWS_ACCOUNT_ID:file-system/$$EFS_FILE_SYSTEM_ID"; \
+	echo "Creating EFS Location"; \
+	EFS_LOCATION_ARN=$$(aws datasync create-location-efs \
+		--efs-filesystem-arn $$EFS_FILESYSTEM_ARN \
+		--ec2-config "SubnetArn=$$EFS_SUBNET_ARN,SecurityGroupArns=$$EFS_SECURITY_GROUP_ARNS" \
+		--query 'LocationArn' --output text); \
+	DATASYNC_S3_ACCESS_ROLE_ARN=$$(aws iam get-role --role-name $(DATASYNC_S3_ACCESS_ROLE_NAME) --query 'Role.Arn' --output text); \
+	S3_LOCATION_ARN=$$(aws datasync create-location-s3 \
+		--s3-bucket-arn arn:aws:s3:::$(BUCKET_NAME) \
+		--s3-config '{ "BucketAccessRoleArn": "'"$$DATASYNC_S3_ACCESS_ROLE_ARN"'" }' \
+		--query 'LocationArn' --output text); \
+	echo "Creating DataSync task to restore data from S3 to EFS"; \
+	TASK_ARN=$$(aws datasync create-task \
+		--source-location-arn $$S3_LOCATION_ARN \
+		--destination-location-arn $$EFS_LOCATION_ARN \
+		--name S3-to-EFS-Restore \
+		--options '{ "OverwriteMode": "ALWAYS", "VerifyMode": "POINT_IN_TIME_CONSISTENT" }' \
+		--query 'TaskArn' --output text); \
+	echo "Starting DataSync task $$TASK_ARN"; \
+	EXECUTION_ARN=$$(aws datasync start-task-execution \
+		--task-arn $$TASK_ARN \
+		--query 'TaskExecutionArn' --output text); \
+	echo "Waiting for DataSync task to complete (Execution ARN: $$EXECUTION_ARN)"; \
+	while true; do \
+		STATUS=$$(aws datasync describe-task-execution \
+			--task-execution-arn $$EXECUTION_ARN \
+			--query 'Status' --output text); \
+		BYTES_TRANSFERRED=$$(aws datasync describe-task-execution \
+			--task-execution-arn $$EXECUTION_ARN \
+			--query 'BytesTransferred' --output text); \
+		BYTES_WRITTEN=$$(aws datasync describe-task-execution \
+			--task-execution-arn $$EXECUTION_ARN \
+			--query 'BytesWritten' --output text); \
+		if [ "$$BYTES_TRANSFERRED" != "None" ] && [ "$$BYTES_WRITTEN" != "None" ] && [ "$$BYTES_TRANSFERRED" -ne 0 ]; then \
+			PERCENT=$$(echo "scale=2; $$BYTES_WRITTEN * 100 / $$BYTES_TRANSFERRED" | bc); \
+			echo "Task status: $$STATUS, Progress: $$PERCENT%"; \
+		else \
+			echo "Task status: $$STATUS, Progress: Calculating..."; \
+		fi; \
+		if [ "$$STATUS" = "SUCCESS" ]; then \
+			echo "DataSync task completed successfully"; \
+			break; \
+		elif [ "$$STATUS" = "ERROR" ]; then \
+			ERROR_CODE=$$(aws datasync describe-task-execution \
+				--task-execution-arn $$EXECUTION_ARN \
+				--query 'Result.ErrorCode' --output text); \
+			ERROR_DETAIL=$$(aws datasync describe-task-execution \
+				--task-execution-arn $$EXECUTION_ARN \
+				--query 'Result.ErrorDetail' --output text); \
+			echo "DataSync task failed with error code: $$ERROR_CODE"; \
+			echo "Error details: $$ERROR_DETAIL"; \
+			exit 1; \
+		else \
+			sleep 10; \
+		fi; \
+	done; \
+	echo "Cleaning up DataSync task and locations"; \
+	aws datasync delete-task --task-arn $$TASK_ARN; \
+	aws datasync delete-location --location-arn $$EFS_LOCATION_ARN; \
+	aws datasync delete-location --location-arn $$S3_LOCATION_ARN
 
 # Downloads data from S3
-download-from-s3:
-	echo "Unimplemented"
+download-from-s3: create-s3-bucket
+	@echo "Initiating download of S3 bucket ($(BUCKET_NAME)) to ./s3-backup"
+	@aws s3 sync s3://$(BUCKET_NAME)/ ./s3-backup/
 
 # Uploads data to S3
 upload-to-s3:
-	echo "Unimplemented"
+	@echo "Initiating upload of ./s3-backup to S3 bucket ($(BUCKET_NAME))"
+	@aws s3 sync ./s3-backup/ s3://$(BUCKET_NAME)/
 
 # Deletes S3 bucket
 delete-s3-bucket:
-	echo "Unimplemented"
+	@echo "Deleting S3 bucket: $(BUCKET_NAME)"
+	@aws s3 rb s3://$(BUCKET_NAME) --force
+
+
+
+
+
+
+
+
+
+
+
+######################
+# S3 Backups         #
+######################
+
+# BUCKET_NAME := $(shell terraform output -raw cluster_name)-bucket
+
+# # Creates S3 bucket (does nothing if already exists)
+# create-s3-bucket:
+# 	@echo "Creating S3 bucket: $(BUCKET_NAME)"
+
+
+# # Copies data from EFS to S3
+# backup-to-s3-from-s3: create-s3-bucket
+# 	@echo "Backing-up data from EFS to S3 bucket: $(BUCKET_NAME)"
+
+# # Restores data from S3 back to EFS
+# restore-to-efs-from-s3:
+# 	@echo "Restoring data from S3 bucket ($(BUCKET_NAME)) to EFS"
+
+# # Downloads data from S3
+# download-from-s3: create-s3-bucket
+# 	@echo "Initiating download of S3 bucket ($(BUCKET_NAME)) to ./s3-backup"
+
+# # Uploads data to S3
+# upload-to-s3:
+# 	@echo "Initiating upload of ./s3-backup to S3 bucket ($(BUCKET_NAME))"
+
+# # Deletes S3 bucket
+# delete-s3-bucket:
+# 	@echo "Deleting S3 bucket: $(BUCKET_NAME)"
+
+
+
+
+
+
+
