feat: Add environment variable checks, enhance SSH key setup, and update .gitignore
- Add checks for environment variables to ensure the presence of .env file for DB credentials
- Enhance SSH key setup by skipping key generation for Jenkins user
- Update .gitignore to include .env and *.log files
- Log build duration for better transparency

diff --git a/starexec-containerised/Makefile b/starexec-containerised/Makefile
--- a/starexec-containerised/Makefile
+++ b/starexec-containerised/Makefile
@@ -2,19 +2,40 @@ SHELL := /bin/bash
 
 USER=$(shell whoami)
 PODMAN_SOCKET_PATH="/run/user/1000/podman/podman.sock"
+VERSION ?= latest
 
 .PHONY: all starexec clean cleanVolumes connect
 all: starexec
 
 starexec:
-	echo "using ssh-keygen to make pub/priv keys in the current directory"
-	echo "(only if they don't already exist)"
-	[ -f starexec_podman_key ] || ssh-keygen -t ed25519 -N '' -f starexec_podman_key 
+	@if [ ! -f .env ]; then \
+			echo "Error: .env file not found. Please create it with required credentials."; \
+			echo "Example contents:"; \
+			echo "DB_USER=se_admin"; \
+			echo "DB_PASS=your_password_here"; \
+			exit 1; \
+	fi
 
-	# Make this key is trusted by the host.
-	ssh-copy-id -i starexec_podman_key.pub ${USER}@localhost
-	
-	podman build --no-cache -t starexec . --ulimit="nofile=100000:100000"
+	@if [ "$(USER)" != "jenkins" ]; then \
+		echo "using ssh-keygen to make pub/priv keys in the current directory"; \
+		echo "(only if they don't already exist)"; \
+		[ -f starexec_podman_key ] || ssh-keygen -t ed25519 -N '' -f starexec_podman_key; \
+		ssh-keyscan -H localhost >> ~/.ssh/known_hosts; \
+		ssh-copy-id -i starexec_podman_key.pub ${USER}@localhost; \
+	else \
+		echo "Skipping SSH key setup for Jenkins user."; \
+	fi
+
+	VERSION=${VERSION} && \
+	START_TIME=$$(date +%Y-%m-%d\ %H:%M:%S) && echo "Build started at: $$START_TIME" | tee build-$$VERSION.log && \
+	time podman build \
+			--build-arg DB_USER=$$(grep DB_USER .env | cut -d '=' -f2) \
+			--build-arg DB_PASS=$$(grep DB_PASS .env | cut -d '=' -f2) \
+			-t starexec:$$VERSION . \
+			--no-cache \
+			--ulimit="nofile=100000:100000" 2> >(tee -a build-$$VERSION.log >&2) && \
+	END_TIME=$$(date +%Y-%m-%d\ %H:%M:%S) && echo "Build finished at: $$END_TIME" | tee -a build-$$VERSION.log && \
+	echo "Build duration: $$(date -u -d @$$(( $$(date -d "$$END_TIME" +%s) - $$(date -d "$$START_TIME" +%s) )) +%H:%M:%S)" | tee -a build-$$VERSION.log
 
 run:
 	podman run --network=host --rm -it -v volDB:/var/lib/mysql \
